[2023-08-18 20:04:17,430] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Products_ETL.get_data manual__2023-08-18T20:04:09.740595+00:00 [queued]>
[2023-08-18 20:04:17,437] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Products_ETL.get_data manual__2023-08-18T20:04:09.740595+00:00 [queued]>
[2023-08-18 20:04:17,438] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-08-18 20:04:17,438] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2023-08-18 20:04:17,439] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-08-18 20:04:17,447] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): get_data> on 2023-08-18 20:04:09.740595+00:00
[2023-08-18 20:04:17,471] {standard_task_runner.py:52} INFO - Started process 7837 to run task
[2023-08-18 20:04:17,475] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'Products_ETL', 'get_data', 'manual__2023-08-18T20:04:09.740595+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmpt12yes7l', '--error-file', '/tmp/tmp2sjvqtvs']
[2023-08-18 20:04:17,476] {standard_task_runner.py:80} INFO - Job 11: Subtask get_data
[2023-08-18 20:04:17,537] {task_command.py:371} INFO - Running <TaskInstance: Products_ETL.get_data manual__2023-08-18T20:04:09.740595+00:00 [running]> on host 0110d0e687e9
[2023-08-18 20:04:17,574] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:202 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2023-08-18 20:04:17,615] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Sol
AIRFLOW_CTX_DAG_ID=Products_ETL
AIRFLOW_CTX_TASK_ID=get_data
AIRFLOW_CTX_EXECUTION_DATE=2023-08-18T20:04:09.740595+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-08-18T20:04:09.740595+00:00
[2023-08-18 20:04:17,617] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/functions.py", line 25, in getData
    for i in range(1, pages + 1):
TypeError: can only concatenate str (not "int") to str
[2023-08-18 20:04:17,627] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=Products_ETL, task_id=get_data, execution_date=20230818T200409, start_date=20230818T200417, end_date=20230818T200417
[2023-08-18 20:04:17,633] {standard_task_runner.py:97} ERROR - Failed to execute job 11 for task get_data (can only concatenate str (not "int") to str; 7837)
[2023-08-18 20:04:17,648] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-08-18 20:04:17,683] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
