[2023-08-22 14:35:55,345] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: new_etl.crear_tabla manual__2023-08-22T14:20:35.102438+00:00 [queued]>
[2023-08-22 14:35:55,364] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: new_etl.crear_tabla manual__2023-08-22T14:20:35.102438+00:00 [queued]>
[2023-08-22 14:35:55,365] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-08-22 14:35:55,365] {taskinstance.py:1377} INFO - Starting attempt 4 of 4
[2023-08-22 14:35:55,366] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-08-22 14:35:55,399] {taskinstance.py:1397} INFO - Executing <Task(RedshiftSQLOperator): crear_tabla> on 2023-08-22 14:20:35.102438+00:00
[2023-08-22 14:35:55,420] {standard_task_runner.py:52} INFO - Started process 7723 to run task
[2023-08-22 14:35:55,430] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'new_etl', 'crear_tabla', 'manual__2023-08-22T14:20:35.102438+00:00', '--job-id', '181', '--raw', '--subdir', 'DAGS_FOLDER/etl2.py', '--cfg-path', '/tmp/tmp9clsiwwq', '--error-file', '/tmp/tmp0im7iwah']
[2023-08-22 14:35:55,433] {standard_task_runner.py:80} INFO - Job 181: Subtask crear_tabla
[2023-08-22 14:35:55,547] {task_command.py:371} INFO - Running <TaskInstance: new_etl.crear_tabla manual__2023-08-22T14:20:35.102438+00:00 [running]> on host 0110d0e687e9
[2023-08-22 14:35:55,665] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Sol
AIRFLOW_CTX_DAG_ID=new_etl
AIRFLOW_CTX_TASK_ID=crear_tabla
AIRFLOW_CTX_EXECUTION_DATE=2023-08-22T14:20:35.102438+00:00
AIRFLOW_CTX_TRY_NUMBER=4
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-08-22T14:20:35.102438+00:00
[2023-08-22 14:35:55,666] {redshift_sql.py:76} INFO - Executing statement: 
        create table if not exists sol_debenedet_coderhouse.products_new (
            _id varchar(25),
            title varchar(25),
            price float,
            createdAt timestamp,
            updatedAt timestamp,
            slug varchar(100),
            category__id varchar(25),
            category_name varchar(50),
            category_slug varchar(100),
            createdBy_role varchar(25),
            createdBy__id varchar(25),
            createdBy_name varchar(25),
            primary key(_id, createdAt)
            );
            
[2023-08-22 14:35:55,683] {base.py:68} INFO - Using connection ID 'redshift-coderhouse' for task execution.
[2023-08-22 14:35:57,049] {dbapi.py:231} INFO - Running statement: 
        create table if not exists sol_debenedet_coderhouse.products_new (
            _id varchar(25),
            title varchar(25),
            price float,
            createdAt timestamp,
            updatedAt timestamp,
            slug varchar(100),
            category__id varchar(25),
            category_name varchar(50),
            category_slug varchar(100),
            createdBy_role varchar(25),
            createdBy__id varchar(25),
            createdBy_name varchar(25),
            primary key(_id, createdAt)
            );
            , parameters: None
[2023-08-22 14:35:57,249] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/redshift_connector/core.py", line 1631, in execute
    ps = cache["ps"][key]
KeyError: ('\n        create table if not exists sol_debenedet_coderhouse.products_new (\n            _id varchar(25),\n            title varchar(25),\n            price float,\n            createdAt timestamp,\n            updatedAt timestamp,\n            slug varchar(100),\n            category__id varchar(25),\n            category_name varchar(50),\n            category_slug varchar(100),\n            createdBy_role varchar(25),\n            createdBy__id varchar(25),\n            createdBy_name varchar(25),\n            primary key(_id, createdAt)\n            );\n            ', ())

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/operators/redshift_sql.py", line 78, in execute
    hook.run(self.sql, autocommit=self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 211, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 235, in _run_command
    cur.execute(sql_statement)
  File "/home/airflow/.local/lib/python3.7/site-packages/redshift_connector/cursor.py", line 240, in execute
    self._c.execute(self, operation, args)
  File "/home/airflow/.local/lib/python3.7/site-packages/redshift_connector/core.py", line 1701, in execute
    self.handle_messages(cursor)
  File "/home/airflow/.local/lib/python3.7/site-packages/redshift_connector/core.py", line 1969, in handle_messages
    raise self.error
redshift_connector.error.ProgrammingError: {'S': 'ERROR', 'C': '3F000', 'M': 'schema "sol_debenedet_coderhouse" does not exist', 'F': '../src/pg/src/mssql/mssql_utils.c', 'L': '244', 'R': 'processRelationInternal'}
[2023-08-22 14:35:57,293] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=new_etl, task_id=crear_tabla, execution_date=20230822T142035, start_date=20230822T143555, end_date=20230822T143557
[2023-08-22 14:35:57,309] {standard_task_runner.py:97} ERROR - Failed to execute job 181 for task crear_tabla ({'S': 'ERROR', 'C': '3F000', 'M': 'schema "sol_debenedet_coderhouse" does not exist', 'F': '../src/pg/src/mssql/mssql_utils.c', 'L': '244', 'R': 'processRelationInternal'}; 7723)
[2023-08-22 14:35:57,360] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-08-22 14:35:57,430] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
