[2023-08-18 20:04:57,889] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Products_ETL.get_data manual__2023-08-18T20:01:49.738866+00:00 [queued]>
[2023-08-18 20:04:57,896] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Products_ETL.get_data manual__2023-08-18T20:01:49.738866+00:00 [queued]>
[2023-08-18 20:04:57,896] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-08-18 20:04:57,897] {taskinstance.py:1377} INFO - Starting attempt 2 of 6
[2023-08-18 20:04:57,897] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-08-18 20:04:57,905] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): get_data> on 2023-08-18 20:01:49.738866+00:00
[2023-08-18 20:04:57,919] {standard_task_runner.py:52} INFO - Started process 7878 to run task
[2023-08-18 20:04:57,923] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'Products_ETL', 'get_data', 'manual__2023-08-18T20:01:49.738866+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmpvmrcd3t_', '--error-file', '/tmp/tmp4z2nq2ts']
[2023-08-18 20:04:57,923] {standard_task_runner.py:80} INFO - Job 12: Subtask get_data
[2023-08-18 20:04:58,003] {task_command.py:371} INFO - Running <TaskInstance: Products_ETL.get_data manual__2023-08-18T20:01:49.738866+00:00 [running]> on host 0110d0e687e9
[2023-08-18 20:04:58,034] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:202 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2023-08-18 20:04:58,062] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Sol
AIRFLOW_CTX_DAG_ID=Products_ETL
AIRFLOW_CTX_TASK_ID=get_data
AIRFLOW_CTX_EXECUTION_DATE=2023-08-18T20:01:49.738866+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-08-18T20:01:49.738866+00:00
[2023-08-18 20:04:58,064] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/functions.py", line 25, in getData
    for i in range(1, pages + 1):
TypeError: can only concatenate str (not "int") to str
[2023-08-18 20:04:58,073] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=Products_ETL, task_id=get_data, execution_date=20230818T200149, start_date=20230818T200457, end_date=20230818T200458
[2023-08-18 20:04:58,078] {standard_task_runner.py:97} ERROR - Failed to execute job 12 for task get_data (can only concatenate str (not "int") to str; 7878)
[2023-08-18 20:04:58,095] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-08-18 20:04:58,125] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
