[2023-08-18 20:01:03,788] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Products_ETL.get_data manual__2023-08-18T19:57:57.283364+00:00 [queued]>
[2023-08-18 20:01:03,795] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Products_ETL.get_data manual__2023-08-18T19:57:57.283364+00:00 [queued]>
[2023-08-18 20:01:03,796] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-08-18 20:01:03,796] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2023-08-18 20:01:03,797] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-08-18 20:01:03,805] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): get_data> on 2023-08-18 19:57:57.283364+00:00
[2023-08-18 20:01:03,816] {standard_task_runner.py:52} INFO - Started process 7625 to run task
[2023-08-18 20:01:03,820] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'Products_ETL', 'get_data', 'manual__2023-08-18T19:57:57.283364+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmpymrgy47r', '--error-file', '/tmp/tmp4grkt2e_']
[2023-08-18 20:01:03,821] {standard_task_runner.py:80} INFO - Job 6: Subtask get_data
[2023-08-18 20:01:03,874] {task_command.py:371} INFO - Running <TaskInstance: Products_ETL.get_data manual__2023-08-18T19:57:57.283364+00:00 [running]> on host 0110d0e687e9
[2023-08-18 20:01:03,908] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:202 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2023-08-18 20:01:03,936] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Sol
AIRFLOW_CTX_DAG_ID=Products_ETL
AIRFLOW_CTX_TASK_ID=get_data
AIRFLOW_CTX_EXECUTION_DATE=2023-08-18T19:57:57.283364+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-08-18T19:57:57.283364+00:00
[2023-08-18 20:01:03,938] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/functions.py", line 25, in getData
    for i in range(1, pages + 1):
TypeError: can only concatenate str (not "int") to str
[2023-08-18 20:01:03,947] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=Products_ETL, task_id=get_data, execution_date=20230818T195757, start_date=20230818T200103, end_date=20230818T200103
[2023-08-18 20:01:03,954] {standard_task_runner.py:97} ERROR - Failed to execute job 6 for task get_data (can only concatenate str (not "int") to str; 7625)
[2023-08-18 20:01:03,993] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-08-18 20:01:04,028] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
